# Header

menu:
  主页: /
  js: /tags/js
  学习笔记: /tags/学习笔记

# SubNav
subnav:
  #github: "#"
  #weibo: "#"
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

#rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
#root: 

# Content
excerpt_link: 阅读全文
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: true

reward_type: 2
reward_wording: '谢谢你请我吃糖果'
alipay: http://og08ttv6v.bkt.clouddn.com/IMG_0682.JPG
# Miscellaneous
google_analytics: ''
favicon: http://og08ttv6v.bkt.clouddn.com/favicon.png

#你的头像url
avatar: http://og08ttv6v.bkt.clouddn.com/user-icon1.gif

#是否开启分享
share_jia: true
share_addthis: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: liamw

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false

smart_menu:
  innerArchive: false
  tagcloud: false
  friends: 友链
  # aboutme: 关于我

friends:
  可达鸭: https://io.n7then.com
  shawn: http://shawnzeng.com
  sabi - 我有一壶酒,足矣慰风霜: https://sa.bi
  Troy: https://itroy.cc
  王鹏飞: https://doctorfei.github.io/
#  友情链接2: http://localhost:4000/
#  友情链接3: http://localhost:4000/
#  友情链接4: http://localhost:4000/
#  友情链接5: http://localhost:4000/
#  友情链接6: http://localhost:4000/
#
# aboutme: 前端小萌新<br/><br/>奋发努力

toc: true